services:
  backend:
    build: ./backend
    container_name: election_backend
    ports:
      - "8000:8000"
    working_dir: /app/src
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./model_registry:/model_registry:ro
      - ./backend/src:/app/src:ro
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: election_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend